name: Deploy ASP.NET Core to Somee

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar paquetes
        run: dotnet restore

      - name: Publicar proyecto
        run: dotnet publish -c Release -o publish

      - name: Subir por FTP a Somee
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: consultorprecio.somee.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /www.consultorprecio.somee.com/
